name: base_app
description: A Base App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  dio_cache_interceptor_hive_store: ^3.1.0
  dio_cache_interceptor: ^3.2.2
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  url_launcher: ^6.0.18
  image_picker: ^0.8.4+4
  cached_network_image: ^3.2.0
  auto_route: ^3.2.3+1
  fluttertoast: ^8.0.8
  logger: ^1.1.0
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  badges: ^2.0.2
  #网络状态检查
  connectivity_plus: ^2.2.0
  #包信息
  package_info_plus: ^1.3.0
  #异常上报
  sentry_flutter: ^6.2.2
  #-----------------推送------------
  firebase_messaging: ^11.2.5

  #---------------------------------
  lottie: ^1.2.1
  # 侧滑选项
  flutter_slidable: ^1.2.0
  photo_view: ^0.13.0
  video_player: ^2.2.14
#  better_player: ^0.0.81
  qr_code_scanner: ^0.6.1
  #日历
  table_calendar: ^3.0.3
  #虚线
  dotted_border: ^2.0.0+2

  flutter_easyloading: ^3.0.3
  dropdown_search: ^2.0.1

dependency_overrides:
  #防止熄屏
  wakelock: ^0.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  json_serializable:
  flutter_native_splash: ^1.3.3
  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true
